In [ ]:
import numpy as np
arr3d = np.array([[[11,22,33],[1,2,3],[111,222,333]],[[999,88,77],[9,8,7],[999,888,777]],[[55,66,77],[7,6,5],[55,8,7]]])
arr3d

In [7]:
arr3d.ndim

3

In [14]:
arr3d[2][1][2]

5

In [54]:
array1 = np.array([[2,4,6,8,10],[1,2,3,4,5],[4,0,6,2,5],[6,6,1,5,3],[7,5,1,6,5],[8,2,4,9,7]])
array1

array([[ 2,  4,  6,  8, 10],
       [ 1,  2,  3,  4,  5],
       [ 4,  0,  6,  2,  5],
       [ 6,  6,  1,  5,  3],
       [ 7,  5,  1,  6,  5],
       [ 8,  2,  4,  9,  7]])

In [55]:
array1[2:4,1:5]

array([[0, 6, 2, 5],
       [6, 1, 5, 3]])

In [31]:
arr = np.arange(1,37).reshape(6,6)
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [45]:
#arr[row,column]
arr[1:5 ,:]

array([[ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [52]:
arr[2:4,-1:]

array([[18],
       [24]])

In [56]:
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [64]:
#stepping
arr[1::2,::2]

array([[ 7,  9, 11],
       [19, 21, 23],
       [31, 33, 35]])

In [86]:
names = np.array(["ayesha", "ariba","ayesha","hamza","ariba"])
data = np.random.randn(5,5)
print(names)
data

['ayesha' 'ariba' 'ayesha' 'hamza' 'ariba']


array([[-1.94582775,  2.12982948, -1.53518128, -0.9577961 ,  0.84377339],
       [ 0.81887251,  0.24345549, -0.37342718, -0.343761  ,  0.03864684],
       [ 0.17189785,  1.92265364,  0.49314437, -0.95789504, -0.53177197],
       [-1.33481579, -0.43825588,  0.37981408, -1.04526572,  0.80497229],
       [ 0.61531353, -1.0734149 , -1.43777304, -0.76157776, -0.05245491]])

      Booleanindexing


In [68]:
data>1

array([[False,  True, False],
       [False, False, False]])

In [78]:
data

array([[-0.5276532 , -0.11178338, -0.53180993],
       [-0.97169551,  0.33343593,  0.77656737]])

In [81]:
data[data>1]

array([], dtype=float64)

In [87]:
data[names == "ayesha"]

array([[-1.94582775,  2.12982948, -1.53518128, -0.9577961 ,  0.84377339],
       [ 0.17189785,  1.92265364,  0.49314437, -0.95789504, -0.53177197]])

In [92]:
bol = np.array([True,True,False,False,True],dtype = "bool")
data
data[bol]

array([[-1.94582775,  2.12982948, -1.53518128, -0.9577961 ,  0.84377339],
       [ 0.81887251,  0.24345549, -0.37342718, -0.343761  ,  0.03864684],
       [ 0.61531353, -1.0734149 , -1.43777304, -0.76157776, -0.05245491]])

In [96]:
names
condition = names!= "ariba"
data[~condition]

array([[ 0.81887251,  0.24345549, -0.37342718, -0.343761  ,  0.03864684],
       [ 0.61531353, -1.0734149 , -1.43777304, -0.76157776, -0.05245491]])

In [97]:
condition

array([ True, False,  True,  True, False])

In [99]:
data[condition,1:3]

array([[ 2.12982948, -1.53518128],
       [ 1.92265364,  0.49314437],
       [-0.43825588,  0.37981408]])

In [103]:
#numpy and or
cond = (names == "ayesha") & (names == "ariba")
print(cond)

[False False False False False]


           Fancyindexing

In [108]:
arr = np.empty((8,4))
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [113]:
arr[[1,3,4],[2,1,0]]

array([1., 3., 4.])

In [118]:
newarr = np.arange(1,37).reshape(6,6)
newarr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [119]:
newarr[[5,4,3,2,1]] #fancyarray

array([[31, 32, 33, 34, 35, 36],
       [25, 26, 27, 28, 29, 30],
       [19, 20, 21, 22, 23, 24],
       [13, 14, 15, 16, 17, 18],
       [ 7,  8,  9, 10, 11, 12]])

In [122]:
print(newarr)
newarr[[5,4,3,2,1,0],[5,4,3,2,1,0]] #fancyarray

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


array([36, 29, 22, 15,  8,  1])

In [125]:
#2d fancy array
newarr[[1,5,4,3]][:,[0,1,3]]
# 1[0,1,3],5[0,1,3],4[0,1,3],3[0,1,3]]
# (1,0),(1,1),(1,3),(5,0),(5,1),(5,1),(5,3),...
                


array([[ 7,  8, 10],
       [31, 32, 34],
       [25, 26, 28],
       [19, 20, 22]])

In [127]:
newarr.transpose()

array([[ 1,  7, 13, 19, 25, 31],
       [ 2,  8, 14, 20, 26, 32],
       [ 3,  9, 15, 21, 27, 33],
       [ 4, 10, 16, 22, 28, 34],
       [ 5, 11, 17, 23, 29, 35],
       [ 6, 12, 18, 24, 30, 36]])

In [133]:
secarr = np.arange(4,40).reshape(6,6)
np.concatenate([newarr,secarr],axis = 1)

array([[ 1,  2,  3,  4,  5,  6,  4,  5,  6,  7,  8,  9],
       [ 7,  8,  9, 10, 11, 12, 10, 11, 12, 13, 14, 15],
       [13, 14, 15, 16, 17, 18, 16, 17, 18, 19, 20, 21],
       [19, 20, 21, 22, 23, 24, 22, 23, 24, 25, 26, 27],
       [25, 26, 27, 28, 29, 30, 28, 29, 30, 31, 32, 33],
       [31, 32, 33, 34, 35, 36, 34, 35, 36, 37, 38, 39]])

In [138]:
np.hstack([newarr,secarr])

array([[ 1,  2,  3,  4,  5,  6,  4,  5,  6,  7,  8,  9],
       [ 7,  8,  9, 10, 11, 12, 10, 11, 12, 13, 14, 15],
       [13, 14, 15, 16, 17, 18, 16, 17, 18, 19, 20, 21],
       [19, 20, 21, 22, 23, 24, 22, 23, 24, 25, 26, 27],
       [25, 26, 27, 28, 29, 30, 28, 29, 30, 31, 32, 33],
       [31, 32, 33, 34, 35, 36, 34, 35, 36, 37, 38, 39]])

In [143]:
print(newarr)
np.vsplit(newarr,2)
np.hsplit(newarr,3)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


[array([[ 1,  2],
        [ 7,  8],
        [13, 14],
        [19, 20],
        [25, 26],
        [31, 32]]), array([[ 3,  4],
        [ 9, 10],
        [15, 16],
        [21, 22],
        [27, 28],
        [33, 34]]), array([[ 5,  6],
        [11, 12],
        [17, 18],
        [23, 24],
        [29, 30],
        [35, 36]])]