In [211]:
import numpy as np

In [84]:
arr = np.arange(1,17).reshape(4,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [85]:
a = np.array([2,-4,6,-8,3,2])
b = np.array([7,5,3,-2,9,-5])
float_arr = np.array([2.3,5.44,-6.99,9.99])
print("a = ",a)
print("b = ",b)
print("float_array = ",float_arr )

a =  [ 2 -4  6 -8  3  2]
b =  [ 7  5  3 -2  9 -5]
float_array =  [ 2.3   5.44 -6.99  9.99]


In [86]:
np.maximum(a,b)

array([ 7,  5,  6, -2,  9,  2])

In [87]:
np.cumsum(a)

array([ 2, -2,  4, -4, -1,  1], dtype=int32)

In [88]:
np.abs(a)

array([2, 4, 6, 8, 3, 2])

In [89]:
remainder, whole_part = np.modf(float_arr)
print("remainder = ",remainder)
print("whole_part = ",whole_part)

remainder =  [ 0.3   0.44 -0.99  0.99]
whole_part =  [ 2.  5. -6.  9.]


In [90]:
np.cumsum(arr,axis = 0)

array([[ 1,  2,  3,  4],
       [ 6,  8, 10, 12],
       [15, 18, 21, 24],
       [28, 32, 36, 40]], dtype=int32)

In [91]:
arr.cumsum(axis = 1)

array([[ 1,  3,  6, 10],
       [ 5, 11, 18, 26],
       [ 9, 19, 30, 42],
       [13, 27, 42, 58]], dtype=int32)

In [92]:
arr.cumprod(axis = 0)

array([[   1,    2,    3,    4],
       [   5,   12,   21,   32],
       [  45,  120,  231,  384],
       [ 585, 1680, 3465, 6144]], dtype=int32)

In [93]:
a

array([ 2, -4,  6, -8,  3,  2])

In [94]:
a.sum()

1

In [95]:
print(arr)
arr.sum(axis = 1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


array([10, 26, 42, 58])

In [96]:
arr.mean(axis = 1)

array([ 2.5,  6.5, 10.5, 14.5])

In [97]:
a.std() #standard deviation

4.705198071164368

In [98]:
a.var() #variance

22.138888888888886

In [99]:
a.argmin() #index if minimum element

3

In [100]:
a.argmax() #index of maximum element

2

In [101]:
a.min()

-8

In [102]:
a.max()

6

In [103]:
dir(__builtins__)

['ArithmeticError',
 'AssertionError',
 'AttributeError',
 'BaseException',
 'BlockingIOError',
 'BrokenPipeError',
 'BufferError',
 'BytesWarning',
 'ChildProcessError',
 'ConnectionAbortedError',
 'ConnectionError',
 'ConnectionRefusedError',
 'ConnectionResetError',
 'DeprecationWarning',
 'EOFError',
 'Ellipsis',
 'EnvironmentError',
 'Exception',
 'False',
 'FileExistsError',
 'FileNotFoundError',
 'FloatingPointError',
 'FutureWarning',
 'GeneratorExit',
 'IOError',
 'ImportError',
 'ImportWarning',
 'IndentationError',
 'IndexError',
 'InterruptedError',
 'IsADirectoryError',
 'KeyError',
 'KeyboardInterrupt',
 'LookupError',
 'MemoryError',
 'ModuleNotFoundError',
 'NameError',
 'None',
 'NotADirectoryError',
 'NotImplemented',
 'NotImplementedError',
 'OSError',
 'OverflowError',
 'PendingDeprecationWarning',
 'PermissionError',
 'ProcessLookupError',
 'RecursionError',
 'ReferenceError',
 'ResourceWarning',
 'RuntimeError',
 'RuntimeWarning',
 'StopAsyncIteration',
 'StopIter

In [104]:

b = [1,2,3]
a = np.repeat(b,3)
c = np.tile(b,3)


In [105]:
a

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [106]:
b

[1, 2, 3]

In [107]:
c

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [108]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
a[a==b]

array([2, 2, 4, 4])

In [109]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
a[(a>=5)&(a<=10)]

array([ 6,  9, 10])

In [110]:
a

array([ 2,  6,  1,  9, 10,  3, 27])

In [111]:
b

array([ 7,  2, 10,  2,  7,  4,  9,  4,  9,  8])

In [112]:
c = a[0:-1]

In [113]:
c = np.array([9,3,4,3,2,3])
c

array([9, 3, 4, 3, 2, 3])

In [114]:
a = np.array([1,2,4,6,4,3])
a

array([1, 2, 4, 6, 4, 3])

In [115]:
d = np.maximum(a,c)
d

array([9, 3, 4, 6, 4, 3])

In [116]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [117]:
arr[:,[1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [118]:
arr[[0,2,1],:]

array([[0, 1, 2],
       [6, 7, 8],
       [3, 4, 5]])

In [119]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [120]:
arr[::-1,1:]

array([[7, 8],
       [4, 5],
       [1, 2]])

In [121]:
arr[:,::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [122]:
rand_arr = np.random.uniform(5,10, size=(5,3))
print(rand_arr)

[[6.65184208 8.09531151 5.87582871]
 [7.08177129 6.35983647 7.7468348 ]
 [8.55005608 8.79234641 5.95102779]
 [9.40203541 8.6095679  8.93110253]
 [6.92902431 5.0748102  9.56688311]]


In [123]:
rand_arr = np.random.random([5,3])
rand_arr

array([[0.37604004, 0.55523797, 0.18940988],
       [0.45003427, 0.47111099, 0.82560031],
       [0.72347168, 0.27434019, 0.45192921],
       [0.45855859, 0.45064579, 0.37968957],
       [0.23306678, 0.50404648, 0.30276304]])

In [124]:
a = np.random.ranf((5,3))
a

array([[0.69096736, 0.52487345, 0.87756801],
       [0.06864615, 0.42966231, 0.18192276],
       [0.4283035 , 0.72038484, 0.56267946],
       [0.75774318, 0.34014552, 0.73657509],
       [0.59064323, 0.83370342, 0.50481171]])

In [125]:
q = np.linspace(0,9,6)
q

array([0. , 1.8, 3.6, 5.4, 7.2, 9. ])

In [126]:
q

array([0. , 1.8, 3.6, 5.4, 7.2, 9. ])

In [127]:
a

array([[0.69096736, 0.52487345, 0.87756801],
       [0.06864615, 0.42966231, 0.18192276],
       [0.4283035 , 0.72038484, 0.56267946],
       [0.75774318, 0.34014552, 0.73657509],
       [0.59064323, 0.83370342, 0.50481171]])

In [128]:
b

array([ 7,  2, 10,  2,  7,  4,  9,  4,  9,  8])

In [129]:
c

array([9, 3, 4, 3, 2, 3])

In [130]:
np.array_equal(c,b)

False

In [131]:
np.split(c, 3)

[array([9, 3]), array([4, 3]), array([2, 3])]

In [132]:
d,e,f=np.array_split(c,3)

In [133]:
arr1 = np.array([1,2,3,1,1,1,3,4,6,5])
arr1

array([1, 2, 3, 1, 1, 1, 3, 4, 6, 5])

In [134]:
arr1 = np.unique(arr1)

In [135]:
arr1

array([1, 2, 3, 4, 5, 6])

In [136]:
np.dot(arr.T, arr)


array([[45, 54, 63],
       [54, 66, 78],
       [63, 78, 93]])

In [137]:
np.dot(arr,3)

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [138]:
arr.transpose()

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [139]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [140]:
arr.swapaxes(0,1)

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [141]:
arr2 = np.array([2,4,9,16])
np.sqrt(arr2)

array([1.41421356, 2.        , 3.        , 4.        ])

In [142]:
np.square(arr2)

array([  4,  16,  81, 256], dtype=int32)

In [145]:
a = np.array([1,2,3])
b = np.array([2,4,6])
np.power(a,b)

array([  1,  16, 729], dtype=int32)

In [147]:
arr1

array([1, 2, 3, 4, 5, 6])

In [152]:
arr1[1] = -2
arr1

array([ 1, -2,  3,  4,  5,  6])

In [170]:
points = np.arange(-5, 5, 0.1)
x,y = np.meshgrid(points,points)
x

array([[-5. , -4.9, -4.8, ...,  4.7,  4.8,  4.9],
       [-5. , -4.9, -4.8, ...,  4.7,  4.8,  4.9],
       [-5. , -4.9, -4.8, ...,  4.7,  4.8,  4.9],
       ...,
       [-5. , -4.9, -4.8, ...,  4.7,  4.8,  4.9],
       [-5. , -4.9, -4.8, ...,  4.7,  4.8,  4.9],
       [-5. , -4.9, -4.8, ...,  4.7,  4.8,  4.9]])

In [171]:
points

array([-5.00000000e+00, -4.90000000e+00, -4.80000000e+00, -4.70000000e+00,
       -4.60000000e+00, -4.50000000e+00, -4.40000000e+00, -4.30000000e+00,
       -4.20000000e+00, -4.10000000e+00, -4.00000000e+00, -3.90000000e+00,
       -3.80000000e+00, -3.70000000e+00, -3.60000000e+00, -3.50000000e+00,
       -3.40000000e+00, -3.30000000e+00, -3.20000000e+00, -3.10000000e+00,
       -3.00000000e+00, -2.90000000e+00, -2.80000000e+00, -2.70000000e+00,
       -2.60000000e+00, -2.50000000e+00, -2.40000000e+00, -2.30000000e+00,
       -2.20000000e+00, -2.10000000e+00, -2.00000000e+00, -1.90000000e+00,
       -1.80000000e+00, -1.70000000e+00, -1.60000000e+00, -1.50000000e+00,
       -1.40000000e+00, -1.30000000e+00, -1.20000000e+00, -1.10000000e+00,
       -1.00000000e+00, -9.00000000e-01, -8.00000000e-01, -7.00000000e-01,
       -6.00000000e-01, -5.00000000e-01, -4.00000000e-01, -3.00000000e-01,
       -2.00000000e-01, -1.00000000e-01, -1.77635684e-14,  1.00000000e-01,
        2.00000000e-01,  

In [174]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])
result = [(x if c else y)for x, y, c in zip(xarr, yarr, cond)]
result

[1.1, 2.2, 1.3, 1.4, 2.5]

In [175]:
np.where(cond,xarr,yarr)

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [176]:
arr

array([[ 0,  1,  2],
       [-2, -2, -2],
       [ 6,  7,  8]])

In [177]:
np.where(arr<2,5,8)

array([[5, 5, 8],
       [5, 5, 5],
       [8, 8, 8]])

In [183]:
d = np.arange(12,2,1)
d

array([], dtype=int32)

In [186]:
arr

array([[ 0,  1,  2],
       [-2, -2, -2],
       [ 6,  7,  8]])

In [188]:
arr.sum(axis = 1)

array([ 3, -6, 21])

In [200]:
np.mean(arr)

2.0

In [215]:
large_arr = np.array([1,2,3,4,5,6,7,8,9,10])
large_arr.sort()
len(large_arr)
large_arr[int(0.05 * len(large_arr))]

1

In [219]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

sorted(set(names))



['Bob', 'Joe', 'Will']

In [221]:
np.unique(names)


array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [222]:
values = np.array([6, 0, 0, 3, 2, 5, 6])

In [233]:
nwalks = 500
nsteps = 600
steps = np.random.normal(size = (10,20))
steps

array([[-0.6476805 , -0.76424456, -0.51688477,  0.27134508,  2.85565883,
        -0.6888786 , -0.7612264 ,  1.42232209,  1.07548736, -0.36265668,
        -0.37173187, -0.49572803, -0.77121507, -0.79959766,  0.6929897 ,
         1.42260743, -0.13178522,  0.6361257 ,  1.1782223 , -0.42100704],
       [-0.15946888,  0.44426203,  0.03034836,  0.74058367, -1.64568047,
        -1.25788591, -1.52745261, -2.13635106,  1.23782661, -0.00446554,
         1.25090394,  0.21092625, -0.72568837, -0.7075086 , -0.63627303,
        -1.70997008,  0.86276202,  0.35068433,  0.24232878, -1.48805864],
       [ 0.1731097 ,  0.33691631, -2.2399468 , -0.4730452 , -0.12164976,
         0.05080563,  0.86543467,  1.23731119,  1.09751663, -0.22681438,
        -1.000713  ,  0.64517865, -0.67117462,  1.54097198,  1.64522149,
         0.17039114,  0.85796516, -0.13455094, -0.42322946,  1.42670129],
       [ 0.34012046,  1.43040151, -0.81755045,  0.71701893, -1.24360808,
         0.29075794,  0.5728561 , -0.92467356, -

In [243]:
a = np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [244]:
np.diag(a)

array([ 0,  5, 10, 15])

In [245]:
arr1

array([ 1, -2,  3,  4,  5,  6])

In [242]:
np.diag(arr1)

array([[ 1,  0,  0,  0,  0,  0],
       [ 0, -2,  0,  0,  0,  0],
       [ 0,  0,  3,  0,  0,  0],
       [ 0,  0,  0,  4,  0,  0],
       [ 0,  0,  0,  0,  5,  0],
       [ 0,  0,  0,  0,  0,  6]])

In [250]:
x = np.array([0,1,2,3,4,5,6,7])
y = np.array([9,7,6,5,3,1,2,1])
np.intersect1d(x,y)

array([1, 2, 3, 5, 6, 7])

In [251]:
np.setdiff1d(x,y)

array([0, 4])

In [252]:
np.in1d(x,y)

array([False,  True,  True,  True, False,  True,  True,  True])

In [253]:
np.setxor1d(x,y)

array([0, 4, 9])