In [1]:
print('let begin with numpy')
# numpy is python library
# fast
#convinent/simple
#multi dimentional array support
#less memory consumption



let begin with numpy


In [32]:
import numpy as np
import time
import sys 

numpy_array = np.array([(1,2,3,4),(3,4,5,6)])
print(numpy_array[1][3])

numpy_array1 = np.arange(10)
print(numpy_array1)

print(numpy_array1.astype('float'))



size = 100000

l1 = list(range(size))
l2 = list(range(size))

n1 = np.arange(size)
n2 = np.arange(size)

start = time.time()
res = n1 * n2
print((time.time()-start)*1000)

start = time.time()
result = []
for i in range(0,len(l1)):
    result.append(l1[i] + l2[i])
    
print((time.time()-start)*1000)

l5 = list(range(size))
n5 = np.arange(size)

print(sys.getsizeof(l5))
print(sys.getsizeof(n5))

6
[0 1 2 3 4 5 6 7 8 9]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
1.0004043579101562
44.025421142578125
900112
400096


In [39]:
arr = np.arange(10)
print(arr)
print(arr[5])
print(arr[5:8])
arr[5:8] = 12
print(arr)
arr_slice = arr[5:8]
print(arr_slice)
arr_slice[1] = 123
print(arr_slice)
print(arr)

[0 1 2 3 4 5 6 7 8 9]
5
[5 6 7]
[ 0  1  2  3  4 12 12 12  8  9]
[12 12 12]
[ 12 123  12]
[  0   1   2   3   4  12 123  12   8   9]


In [ ]:
arr[5]
arr[5:8]
arr[5:8] = 12
arr
arr_slice = arr[5:8]
arr_slice