In [8]:
import numpy as np
a = np.array([1,2,3,4,5,6], dtype = "float")
b = a*5
print(b/5)
print(b*2)


[1. 2. 3. 4. 5. 6.]
[10. 20. 30. 40. 50. 60.]


In [11]:
print(a.shape)
print(a.ndim)
c = a.reshape(2,3)
print("c = ",c)
print(c.shape)
print(c.ndim)
print(type(c))

(6,)
1
c =  [[1. 2. 3.]
 [4. 5. 6.]]
(2, 3)
2
<class 'numpy.ndarray'>


                          19 october home practise

In [2]:
import numpy as np

In [17]:
a = np.arange(3,15,3)
Mylist = [2,4,6,8]
print(a*Mylist)
a

[ 6 24 54 96]


array([ 3,  6,  9, 12])

In [18]:
a*2

array([ 6, 12, 18, 24])

In [19]:
Mylist*2

[2, 4, 6, 8, 2, 4, 6, 8]

In [1]:
import numpy as np

In [2]:
a = np.arange(1000)
a

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [7]:
b = np.zeros((2,3,4))
b

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [8]:
b.shape

(2, 3, 4)

In [12]:
c = np.ones((2,3,4))
c

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [14]:
list1 = [2, 3.2, 5.5, -6.4, -2.2, 2.4]
list1

[2, 3.2, 5.5, -6.4, -2.2, 2.4]

In [16]:
a = np.array(list1)
a

array([ 2. ,  3.2,  5.5, -6.4, -2.2,  2.4])

In [17]:
a[1]

3.2

In [18]:
a[1:4]

array([ 3.2,  5.5, -6.4])

In [4]:
arr1 = np.empty((8,2))
arr1

array([[ 3.60440391e+228, -3.38460785e+125],
       [ 4.24437440e+175,  1.74920357e-307],
       [ 1.33360321e+241,  2.89864625e-311],
       [ 6.91039181e-260,  9.37824756e-280],
       [ 4.03162372e-270,  1.92849182e-309],
       [ 1.25160405e-308,  2.11382017e-307],
       [ 5.72778370e+250,  5.04685103e+173],
       [ 5.40673624e+173,  2.25218083e+289]])

In [4]:
a = list(range(10))
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [34]:
b = np.array([1.9,2.0,4.9,6.0])
b

array([1.9, 2. , 4.9, 6. ])

In [21]:
a = [1,8,7,"a",6]
a*2

[1, 8, 7, 'a', 6, 1, 8, 7, 'a', 6]

In [24]:
b.shape

(4,)

In [25]:
b.ndim

1

In [35]:
b.dtype

dtype('float64')

In [53]:
zero = np.zeros((2,4))
a = np.ones_like(b)
a

array([1., 1., 1., 1.])

In [60]:
onelike = np.ones_like(b)
onelike

array([1., 1., 1., 1.])

In [75]:
arr1 = np.arange(10 ,dtype = "int")
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
arr2 = np.arange(10,20)
arr2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [76]:
arr3 = arr1.astype(np.int)
arr3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
arr1**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [81]:
arr1.dtype

dtype('int32')

In [85]:
arr1.astype(float)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [86]:
arr1.dtype

dtype('int32')

In [89]:
arr1 = arr1.astype(np.float)
arr1

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [91]:
arr1

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [14]:
import numpy as np

In [11]:
a = np.array([1,4,5,6,9])
a

array([1, 4, 5, 6, 9])

In [28]:
a = np.array([5,0,2,8,9,8,5,4,6,0])
a

array([5, 0, 2, 8, 9, 8, 5, 4, 6, 0])

In [26]:
b = np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
b[a>b]

array([0, 3, 4, 5])

                         slicing and indexing

In [78]:
a = np.array([2,4,6,8,10,12,14,16,18 ,20,22,24,26])
b = np.array(([7,8,9],[5,7,8],[9,8,5]))
a


array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26])

In [94]:
print(a)
d = a[0:11:2]
d

[ 2  4  6  8 10 12 14 16 18 20 22 24 26]


array([ 2,  6, 10, 14, 18, 22])

In [96]:
b[0,2]

9

In [101]:
a1 = np.array([[1,2,3],[4,5,6],[9,7,5]])
a1.ndim

2

In [102]:
a1[0:,:2]

array([[1, 2],
       [4, 5],
       [9, 7]])

In [103]:
a1[0]

array([1, 2, 3])

In [128]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
names=="Bob"
#data


array([ True, False, False,  True, False, False, False])

In [108]:
data[[names=="Bob"]

array([[-1.46514085, -0.51896717, -1.85084335, -0.13327772],
       [ 0.30318475,  1.21780672, -0.04039218, -0.57091945]])

In [129]:
data

array([[-0.34939376,  0.91599904, -1.16005445,  0.77352921],
       [-1.39650092, -2.06019617, -0.81333591, -0.51271424],
       [-0.85248781,  0.00368067, -1.30845832,  1.38338503],
       [ 0.71611413,  1.55662337, -0.26525304,  0.91626276],
       [ 0.22304059,  1.14808097,  0.80566772,  0.31067977],
       [ 0.88428609, -2.25016132, -1.41615312,  0.75860502],
       [ 0.50338566, -0.19002234,  0.12764138,  0.61892022]])

In [113]:
data[~(names!="Bob")]

array([[-1.46514085, -0.51896717, -1.85084335, -0.13327772],
       [ 0.30318475,  1.21780672, -0.04039218, -0.57091945]])

In [117]:
mask = (names == 'Bob')| (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [135]:
data[data<0]= 9
data

array([[9.00000000e+00, 9.15999038e-01, 9.00000000e+00, 7.73529213e-01],
       [9.00000000e+00, 9.00000000e+00, 9.00000000e+00, 9.00000000e+00],
       [9.00000000e+00, 3.68066827e-03, 9.00000000e+00, 1.38338503e+00],
       [7.16114133e-01, 1.55662337e+00, 9.00000000e+00, 9.16262755e-01],
       [2.23040591e-01, 1.14808097e+00, 8.05667715e-01, 3.10679772e-01],
       [8.84286088e-01, 9.00000000e+00, 9.00000000e+00, 7.58605015e-01],
       [5.03385659e-01, 9.00000000e+00, 1.27641383e-01, 6.18920225e-01]])

In [138]:
a = np.array([[1,9,8,8],[0,9,7,6],[5,4,6,3],[1,4,7,8],[0,8,6,9],[6,4,3,2],[0,5,8,7],[9,7,9,8]])
a

array([[1, 9, 8, 8],
       [0, 9, 7, 6],
       [5, 4, 6, 3],
       [1, 4, 7, 8],
       [0, 8, 6, 9],
       [6, 4, 3, 2],
       [0, 5, 8, 7],
       [9, 7, 9, 8]])

In [139]:
a[[1,3,4],[2,1,0]]

array([7, 4, 0])

In [142]:
np.dot(a.T,a)


array([[144, 120, 144, 115],
       [120, 348, 350, 341],
       [144, 350, 388, 368],
       [115, 341, 368, 371]])

In [143]:
a

array([[1, 9, 8, 8],
       [0, 9, 7, 6],
       [5, 4, 6, 3],
       [1, 4, 7, 8],
       [0, 8, 6, 9],
       [6, 4, 3, 2],
       [0, 5, 8, 7],
       [9, 7, 9, 8]])

In [144]:
b

array([[7, 8, 9],
       [5, 7, 8],
       [9, 8, 5]])

In [145]:
a1

array([[1, 2, 3],
       [4, 5, 6],
       [9, 7, 5]])

In [162]:
a = np.array([-2,3,87,64,32,87,49,36,23,54])
a

array([-2,  3, 87, 64, 32, 87, 49, 36, 23, 54])

In [160]:
b = np.sqrt(a)
b

C:\Users\Ayesha\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([       nan, 1.73205081, 9.32737905, 8.        , 5.65685425,
       9.32737905, 7.        , 6.        , 4.79583152, 7.34846923])

In [161]:
c = np.square(b)
c

array([nan,  3., 87., 64., 32., 87., 49., 36., 23., 54.])

In [156]:
c = np.exp(a)
c

array([7.38905610e+00, 2.00855369e+01, 6.07603023e+37, 6.23514908e+27,
       7.89629602e+13, 6.07603023e+37, 1.90734657e+21, 4.31123155e+15,
       9.74480345e+09, 2.83075330e+23])

In [164]:
d = np.abs(a)
d

array([-2,  3, 87, 64, 32, 87, 49, 36, 23, 54])

In [166]:
d = np.sign(a)
d

array([-1,  1,  1,  1,  1,  1,  1,  1,  1,  1])

In [168]:
c = np.ones_like(a)
c

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [169]:
a = [0,3,0,9,-9,-4,0,1,-1]
a

[0, 3, 0, 9, -9, -4, 0, 1, -1]

In [175]:
np.sign(a)

array([ 0,  1,  0,  1, -1, -1,  0,  1, -1])

In [173]:
print(a)
np.ceil(a)

[0, 3, 0, 9, -9, -4, 0, 1, -1]


array([ 0.,  3.,  0.,  9., -9., -4.,  0.,  1., -1.])

In [178]:
a.np.ceil(9)

AttributeError: 'list' object has no attribute 'np'