In [86]:
import numpy as np
import pandas as pd
from numpy import NAN as nan
a = np.array([1,2,3,4,5,6], dtype = "float")
b = a*5
print(b/5)
print(b*2)


[1. 2. 3. 4. 5. 6.]
[10. 20. 30. 40. 50. 60.]


In [4]:
print(a.shape)
print(a.ndim)
c = a.reshape(2,3)
print("c = ",c)
print(c.shape)
print(c.ndim)
print(type(c))

(6,)
1
c =  [[1. 2. 3.]
 [4. 5. 6.]]
(2, 3)
2
<class 'numpy.ndarray'>


                          19 october home practise

In [2]:
import numpy as np

In [17]:
a = np.arange(3,15,3)
Mylist = [2,4,6,8]
print(a*Mylist)
a

[ 6 24 54 96]


array([ 3,  6,  9, 12])

In [18]:
a*2

array([ 6, 12, 18, 24])

In [19]:
Mylist*2

[2, 4, 6, 8, 2, 4, 6, 8]

In [6]:
import numpy as np

In [7]:
a = np.arange(1000)
a

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [8]:
b = np.zeros((2,3,4))
b

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [9]:
b.shape

(2, 3, 4)

In [10]:
c = np.ones((2,3,4))
c

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [11]:
list1 = [2, 3.2, 5.5, -6.4, -2.2, 2.4]
list1

[2, 3.2, 5.5, -6.4, -2.2, 2.4]

In [12]:
a = np.array(list1)
a

array([ 2. ,  3.2,  5.5, -6.4, -2.2,  2.4])

In [13]:
a[1]

3.2

In [14]:
a[1:4]

array([ 3.2,  5.5, -6.4])

In [15]:
arr1 = np.empty((8,2))
arr1

array([[6.23042070e-307, 4.67296746e-307],
       [1.69121096e-306, 9.34613185e-307],
       [6.23053614e-307, 2.22522597e-306],
       [1.33511969e-306, 1.37962320e-306],
       [9.34604358e-307, 9.79101082e-307],
       [1.78020576e-306, 1.69119873e-306],
       [2.22522868e-306, 1.24611809e-306],
       [8.06632139e-308, 1.60221208e-306]])

In [16]:
a = list(range(10))
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [17]:
b = np.array([1.9,2.0,4.9,6.0])
b

array([1.9, 2. , 4.9, 6. ])

In [18]:
a = [1,8,7,"a",6]
a*2

[1, 8, 7, 'a', 6, 1, 8, 7, 'a', 6]

In [19]:
b.shape

(4,)

In [20]:
b.ndim

1

In [21]:
b.dtype

dtype('float64')

In [22]:
zero = np.zeros((2,4))
a = np.ones_like(b)
a

array([1., 1., 1., 1.])

In [23]:
onelike = np.ones_like(b)
onelike

array([1., 1., 1., 1.])

In [24]:
arr1 = np.arange(10 ,dtype = "int")
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
arr2 = np.arange(10,20)
arr2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [26]:
arr3 = arr1.astype(np.int)
arr3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
arr1**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [28]:
arr1.dtype

dtype('int32')

In [29]:
arr1.astype(float)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [30]:
arr1.dtype

dtype('int32')

In [31]:
arr1 = arr1.astype(np.float)
arr1

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [32]:
arr1

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [33]:
import numpy as np

In [34]:
a = np.array([1,4,5,6,9])
a

array([1, 4, 5, 6, 9])

In [35]:
a = np.array([5,0,2,8,9,8,5,4,6,0])
a

array([5, 0, 2, 8, 9, 8, 5, 4, 6, 0])

In [36]:
b = np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
b[a>b]

array([0, 3, 4, 5])

                         slicing and indexing

In [38]:
a = np.array([2,4,6,8,10,12,14,16,18 ,20,22,24,26])
b = np.array(([7,8,9],[5,7,8],[9,8,5]))
a


array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26])

In [39]:
print(a)
d = a[0:11:2]
d

[ 2  4  6  8 10 12 14 16 18 20 22 24 26]


array([ 2,  6, 10, 14, 18, 22])

In [40]:
b[0,2]

9

In [41]:
a1 = np.array([[1,2,3],[4,5,6],[9,7,5]])
a1.ndim

2

In [42]:
a1[0:,:2]

array([[1, 2],
       [4, 5],
       [9, 7]])

In [43]:
a1[0]

array([1, 2, 3])

In [44]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
names=="Bob"
#data


array([ True, False, False,  True, False, False, False])

In [45]:
data[[names=="Bob"]

SyntaxError: unexpected EOF while parsing (<ipython-input-45-0cc72b585336>, line 1)

In [46]:
data

array([[-0.87673728,  1.05658613,  0.45668415,  0.36553842],
       [-0.69413603,  0.45920169,  0.71469451, -0.18284418],
       [-0.02039   , -0.4534228 ,  0.42253344,  0.5456081 ],
       [ 0.67543335, -0.40401922, -1.20771025, -0.40706717],
       [ 1.18834762,  0.8985411 ,  1.0989284 , -1.17562372],
       [ 0.39453068,  1.37873396,  0.58204418, -0.92571149],
       [ 1.02153796, -1.41171069, -0.93572783, -0.1586721 ]])

In [47]:
data[~(names!="Bob")]

array([[-0.87673728,  1.05658613,  0.45668415,  0.36553842],
       [ 0.67543335, -0.40401922, -1.20771025, -0.40706717]])

In [48]:
mask = (names == 'Bob')| (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [49]:
data[data<0]= 9
data

array([[9.        , 1.05658613, 0.45668415, 0.36553842],
       [9.        , 0.45920169, 0.71469451, 9.        ],
       [9.        , 9.        , 0.42253344, 0.5456081 ],
       [0.67543335, 9.        , 9.        , 9.        ],
       [1.18834762, 0.8985411 , 1.0989284 , 9.        ],
       [0.39453068, 1.37873396, 0.58204418, 9.        ],
       [1.02153796, 9.        , 9.        , 9.        ]])

In [50]:
a = np.array([[1,9,8,8],[0,9,7,6],[5,4,6,3],[1,4,7,8],[0,8,6,9],[6,4,3,2],[0,5,8,7],[9,7,9,8]])
a

array([[1, 9, 8, 8],
       [0, 9, 7, 6],
       [5, 4, 6, 3],
       [1, 4, 7, 8],
       [0, 8, 6, 9],
       [6, 4, 3, 2],
       [0, 5, 8, 7],
       [9, 7, 9, 8]])

In [51]:
a[[1,3,4],[2,1,0]]

array([7, 4, 0])

In [52]:
np.dot(a.T,a)


array([[144, 120, 144, 115],
       [120, 348, 350, 341],
       [144, 350, 388, 368],
       [115, 341, 368, 371]])

In [53]:
a

array([[1, 9, 8, 8],
       [0, 9, 7, 6],
       [5, 4, 6, 3],
       [1, 4, 7, 8],
       [0, 8, 6, 9],
       [6, 4, 3, 2],
       [0, 5, 8, 7],
       [9, 7, 9, 8]])

In [54]:
b

array([[7, 8, 9],
       [5, 7, 8],
       [9, 8, 5]])

In [55]:
a1

array([[1, 2, 3],
       [4, 5, 6],
       [9, 7, 5]])

In [56]:
import numpy as np
a = np.array([-2,3,87,64,32,87,49,36,23,54])
a

array([-2,  3, 87, 64, 32, 87, 49, 36, 23, 54])

In [85]:
b = np.sqrt(a)
b

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974])

In [58]:
c = np.square(b)
c

array([nan,  3., 87., 64., 32., 87., 49., 36., 23., 54.])

In [59]:
c = np.exp(a)
c

array([1.35335283e-01, 2.00855369e+01, 6.07603023e+37, 6.23514908e+27,
       7.89629602e+13, 6.07603023e+37, 1.90734657e+21, 4.31123155e+15,
       9.74480345e+09, 2.83075330e+23])

In [60]:
d = np.abs(a)
d

array([ 2,  3, 87, 64, 32, 87, 49, 36, 23, 54])

In [61]:
d = np.sign(a)
d

array([-1,  1,  1,  1,  1,  1,  1,  1,  1,  1])

In [62]:
c = np.ones_like(a)
c

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [63]:
a = [0,3,0,9,-9,-4,0,1,-1]
a

[0, 3, 0, 9, -9, -4, 0, 1, -1]

In [64]:
np.sign(a)

array([ 0,  1,  0,  1, -1, -1,  0,  1, -1])

In [65]:
print(a)
np.ceil(a)

[0, 3, 0, 9, -9, -4, 0, 1, -1]


array([ 0.,  3.,  0.,  9., -9., -4.,  0.,  1., -1.])

In [66]:
b = np.square(a)
b
#np.ceil(b)

array([ 0,  9,  0, 81, 81, 16,  0,  1,  1], dtype=int32)

In [67]:
empty_arr = np.array([[1,2,3],[4,5,6],[7,6,5]])
empty_arr.shape

(3, 3)

In [68]:
arr = np.arange(32).reshape(8,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [69]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [84]:
arr[[]]

array([], shape=(0, 4), dtype=int32)

In [ ]:
arr.T

In [ ]:
np.dot(arr.T,arr)

In [ ]:
x = np.array([2,3,4,6,9,7,3])
y = np.array([6,4,3,2,1,8,2])

In [ ]:
np.minimum(x,y)

In [ ]:
z = np.asarray(x,dtype = "float")
z

In [ ]:
remainder,whole_part = np.modf(z)
remainder

In [ ]:
whole_part

In [182]:
a = [4,9,16,25,36]
#np.sqrt(a)
np.sqrt(a)

array([2., 3., 4., 5., 6.])

In [183]:
a = np.array([2.44,3.88,-4.33,7.008])
a

array([ 2.44 ,  3.88 , -4.33 ,  7.008])

In [184]:
np.fabs(a)

array([2.44 , 3.88 , 4.33 , 7.008])

In [185]:
np.ceil(a)

array([ 3.,  4., -4.,  8.])

In [186]:
np.floor(a)

array([ 2.,  3., -5.,  7.])

In [72]:
np.sign(a)

array([ 0,  1,  0,  1, -1, -1,  0,  1, -1])

In [73]:
np.rint(a)

array([ 0.,  3.,  0.,  9., -9., -4.,  0.,  1., -1.])

In [74]:
np.isnan(a)

array([False, False, False, False, False, False, False, False, False])

In [75]:
np.isinf(a)

array([False, False, False, False, False, False, False, False, False])

                HANDLING MISSING DATA

In [87]:
df1 = pd.DataFrame({"name" : ["Ayesha","Ariba","Hamza","Alishba"],"Age": [21,19,18,nan],"gender": ["female","female","male","female"]})
df1

name   Age  gender
0   Ayesha  21.0  female
1    Ariba  19.0  female
2    Hamza  18.0    male
3  Alishba   NaN  female

In [90]:
df1.isnull()

name    Age  gender
0  False  False   False
1  False  False   False
2  False  False   False
3  False   True   False

In [91]:
df1.fillna(14)

name   Age  gender
0   Ayesha  21.0  female
1    Ariba  19.0  female
2    Hamza  18.0    male
3  Alishba  14.0  female

In [93]:
df1.dropna()

name   Age  gender
0  Ayesha  21.0  female
1   Ariba  19.0  female
2   Hamza  18.0    male

In [94]:
df1.notnull()

name    Age  gender
0  True   True    True
1  True   True    True
2  True   True    True
3  True  False    True

In [100]:
df1[df1.isnull()]

name  Age gender
0  NaN  NaN    NaN
1  NaN  NaN    NaN
2  NaN  NaN    NaN
3  NaN  NaN    NaN

In [104]:
df1.dropna(how = "any")

name   Age  gender
0  Ayesha  21.0  female
1   Ariba  19.0  female
2   Hamza  18.0    male

In [105]:
df1[3] = [nan,nan,nan,nan]

In [118]:
df1

name   Age  gender   3
0   Ayesha  21.0  female NaN
1    Ariba  19.0  female NaN
2    Hamza  18.0    male NaN
3  Alishba   NaN  female NaN

In [121]:
df1.dropna(axis = 1,how = "any")

name  gender
0   Ayesha  female
1    Ariba  female
2    Hamza    male
3  Alishba  female

In [149]:
df2 = pd.DataFrame(np.random.rand(5,3))
df2

0         1         2
0  0.545502  0.633334  0.742825
1  0.975290  0.169582  0.290224
2  0.952671  0.495648  0.877263
3  0.252657  0.447349  0.386186
4  0.917493  0.544113  0.197066

In [154]:
df2.iloc[3:,1:] = nan
df2

0         1         2
0  0.545502  0.633334  0.742825
1  0.975290  0.169582  0.290224
2  0.952671  0.495648  0.877263
3  0.252657       NaN       NaN
4  0.917493       NaN       NaN

In [157]:
df2.dropna(axis = 1,how = "any")

0
0  0.545502
1  0.975290
2  0.952671
3  0.252657
4  0.917493

In [166]:
df2.fillna({0: 0.5,1:20, 2: 0},inplace = True)

In [167]:
df2

0          1         2
0  0.545502   0.633334  0.742825
1  0.975290   0.169582  0.290224
2  0.952671   0.495648  0.877263
3  0.252657  20.000000  0.000000
4  0.917493  20.000000  0.000000

In [172]:
df3 = pd.DataFrame(np.random.rand(5,3))
df3.iloc[2:4,1:] = nan
df3

0         1         2
0  0.057886  0.976700  0.902662
1  0.730511  0.775677  0.523423
2  0.821754       NaN       NaN
3  0.472534       NaN       NaN
4  0.246560  0.080309  0.066796

In [178]:
df3.fillna(method = "ffill",limit = 1,axis = 1)

0         1         2
0  0.057886  0.976700  0.902662
1  0.730511  0.775677  0.523423
2  0.821754  0.821754       NaN
3  0.472534  0.472534       NaN
4  0.246560  0.080309  0.066796

In [312]:
data=  pd.Series([12,34,21,43,54,nan,76])
np.mean(data)

40.0

In [195]:
data.fillna(data.mean())

0    12.0
1    34.0
2    21.0
3    43.0
4    54.0
5    40.0
6    76.0
dtype: float64

          DATA TRANSFORMATION 

In [197]:
data1 = pd.DataFrame({'k1': ['one', 'two'] * 3 + ['two'], 'k2': [1, 1, 2, 3, 3, 4, 4]})
data1

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [201]:
data1.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [207]:
data1["k3"] = range(7)
data1

k1  k2  k3
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [217]:
data1.drop_duplicates(["k2","k1"])

k1  k2  k3
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5

In [231]:
restaurant = pd.DataFrame({'food': ['bacon', 'pulled pork', 'bacon','Pastrami','corned beef', 'Bacon', 'pastrami', 'honey ham', 'nova lox'],
                           'ounces': [4, 3, 12, 6, 7.5, 8, 3,5, 6]})
restaurant

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [232]:
meat_to_animal = {
 'bacon': 'pig',
 'pulled pork': 'pig',
 'pastrami': 'cow',
 'corned beef': 'cow',
 'honey ham': 'pig',
 'nova lox': 'salmon'
}


In [233]:
lowercased = restaurant["food"].str.lower()
lowercased

0          bacon
1    pulled pork
2          bacon
3       pastrami
4    corned beef
5          bacon
6       pastrami
7      honey ham
8       nova lox
Name: food, dtype: object

In [234]:
restaurant["animal"] = lowercased.map(meat_to_animal)
restaurant

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [235]:
data

0    12.0
1    34.0
2    21.0
3    43.0
4    54.0
5     NaN
6    76.0
dtype: float64

In [236]:
data.replace(34.0,100)

0     12.0
1    100.0
2     21.0
3     43.0
4     54.0
5      NaN
6     76.0
dtype: float64

In [237]:
data.replace(nan,data.mean())

0    12.0
1    34.0
2    21.0
3    43.0
4    54.0
5    40.0
6    76.0
dtype: float64

In [239]:
data.replace({21:30,54:65,nan:1})

0    12.0
1    34.0
2    30.0
3    43.0
4    65.0
5     1.0
6    76.0
dtype: float64

In [243]:
restaurant

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [258]:
transform = lambda x : x[:].upper()
restaurant.index = ["a","b","c","d","e","f","g","h","i"]
restaurant.index = restaurant.index.map(transform)

In [259]:
restaurant

food  ounces  animal
A        bacon     4.0     pig
B  pulled pork     3.0     pig
C        bacon    12.0     pig
D     Pastrami     6.0     cow
E  corned beef     7.5     cow
F        Bacon     8.0     pig
G     pastrami     3.0     cow
H    honey ham     5.0     pig
I     nova lox     6.0  salmon

In [264]:
restaurant.rename(index = {"A": 0,"B":1,"C":2,"D":3})

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
E  corned beef     7.5     cow
F        Bacon     8.0     pig
G     pastrami     3.0     cow
H    honey ham     5.0     pig
I     nova lox     6.0  salmon

In [270]:
restaurant.columns = ["FOOD","OUNCES","ANIMAL"]
restaurant

FOOD  OUNCES  ANIMAL
A        bacon     4.0     pig
B  pulled pork     3.0     pig
C        bacon    12.0     pig
D     Pastrami     6.0     cow
E  corned beef     7.5     cow
F        Bacon     8.0     pig
G     pastrami     3.0     cow
H    honey ham     5.0     pig
I     nova lox     6.0  salmon

In [285]:
ages = [18,25,35,40,60,100]
bins = [22,23,43,26,65,76,36,43,98,54,91]
cat = pd.cut(bins,ages,labels = ["adult","young","youngadult","middelaged","old"])
cat

[adult, adult, middelaged, young, old, ..., youngadult, middelaged, old, middelaged, old]
Length: 11
Categories (5, object): [adult < young < youngadult < middelaged < old]

In [280]:
cat.codes

array([0, 0, 3, 1, 4, 4, 2, 3, 4, 3, 4], dtype=int8)

In [283]:
len(cat)

11

In [284]:
cat.categories

IntervalIndex([(18, 25], (25, 35], (35, 40], (40, 60], (60, 100]],
              closed='right',
              dtype='interval[int64]')

In [297]:
data = np.array([0,1,2,3,21,2,5,7])
pd.cut(data,3,precision = 2)

[(-0.021, 7.0], (-0.021, 7.0], (-0.021, 7.0], (-0.021, 7.0], (14.0, 21.0], (-0.021, 7.0], (-0.021, 7.0], (-0.021, 7.0]]
Categories (3, interval[float64]): [(-0.021, 7.0] < (7.0, 14.0] < (14.0, 21.0]]

In [291]:
data

array([ 1,  2,  3,  4, 54,  3, 21,  2,  5,  7])

In [298]:
pd.qcut(data,3,precision = 2)

[(-0.01, 2.0], (-0.01, 2.0], (-0.01, 2.0], (2.0, 4.33], (4.33, 21.0], (-0.01, 2.0], (4.33, 21.0], (4.33, 21.0]]
Categories (3, interval[float64]): [(-0.01, 2.0] < (2.0, 4.33] < (4.33, 21.0]]

In [305]:
data1 = pd.DataFrame(np.random.randn(50, 4))
data1.abs()


0         1         2         3
0   0.262420  0.055701  0.434648  0.304527
1   0.866636  0.480319  1.091323  0.273115
2   0.395109  1.398844  0.051247  0.532002
3   1.567923  1.046895  2.057663  0.994276
4   2.193469  0.552221  0.844895  0.241903
5   0.590558  0.886606  0.618547  0.321821
6   1.082844  0.570267  1.538206  1.637322
7   1.344133  1.450032  1.082121  0.353347
8   1.735258  1.156509  0.852686  1.755770
9   0.136821  0.013545  0.739256  0.160294
10  0.957856  1.394303  1.364446  0.312134
11  0.592722  0.737115  0.070442  1.446976
12  1.030708  0.595907  1.367401  0.554109
13  0.146224  0.616728  0.048695  0.026319
14  0.140042  1.304624  0.153469  0.416671
15  0.754859  0.450151  0.011075  0.551315
16  0.166967  1.996345  0.089730  0.757644
17  0.786171  1.216698  2.029061  1.725903
18  0.862392  0.836315  1.071531  0.558635
19  0.405092  0.310440  1.162379  0.634934
20  1.173565  1.517626  1.106742  0.410298
21  0.440697  1.362259  1.225998  0.612130
22  0.773146  0.368300  0.662648  0.855087
23  0.699845  0.141117  1.121089  0.272485
24  3.102877  0.196170  0.715180  0.123938
25  0.827633  0.668449  0.323731  1.349611
26  0.558894  0.656734  1.151679  1.282309
27  0.284195  0.998393  0.572021  0.263504
28  0.848060  0.794460  1.316406  1.069220
29  1.227433  0.016455  1.370665  0.648745
30  1.315669  0.836213  1.804778  0.348643
31  0.685226  0.995549  1.135551  0.323217
32  1.251191  1.173872  0.601769  2.292522
33  0.080663  0.419336  0.021170  0.561970
34  0.159220  1.179968  0.365922  1.907350
35  1.356628  0.252363  0.921020  2.047319
36  0.384079  0.735314  0.462220  0.593214
37  0.147694  0.321717  0.746143  1.609250
38  0.467440  0.570631  0.424720  1.863337
39  0.555967  0.132357  0.275980  1.247841
40  0.869984  1.027050  1.543112  0.354084
41  0.563486  0.313680  1.090208  0.554663
42  0.053467  2.315915  0.054099  0.159674
43  0.940165  0.803850  0.665622  1.067583
44  1.159833  0.244484  0.911420  0.299607
45  0.173615  1.868159  0.084914  0.057558
46  1.578962  1.550869  0.491078  2.261805
47  0.849144  1.103864  1.219211  1.139606
48  1.177160  1.271536  2.754927  0.938172
49  0.453924  1.031991  0.184875  1.273639

In [314]:
data.fillna(data.mean(),inplace = True)

In [315]:
data

0    12.0
1    34.0
2    21.0
3    43.0
4    54.0
5    40.0
6    76.0
dtype: float64

In [1]:
data

NameError: name 'data' is not defined